In [1]:
import duckdb
import sys
from pathlib import Path
import pandas as pd 

ROOT_DIR = Path.cwd().parent

if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))
    
    
from src.db.sql_runner import run_query

In [2]:
df_nulos = run_query("01_nulls_check.sql")
df_nulos

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    column_name column_type  pct_nulos  valores_unicos
0         id_24      DOUBLE      99.20              12
1         id_07      DOUBLE      99.13              99
2         id_08      DOUBLE      99.13              94
3         id_21      DOUBLE      99.13             469
4         id_25      DOUBLE      99.13             391
..          ...         ...        ...             ...
429        V317      DOUBLE       0.00           13197
430        V318      DOUBLE       0.00           10729
431        V319      DOUBLE       0.00            5914
432        V320      DOUBLE       0.00            7477
433        V290      DOUBLE       0.00              67

[434 rows x 4 columns]

In [3]:
colunas_descarte = df_nulos[df_nulos['pct_nulos'] > 85]['column_name'].tolist()

colunas_mantidas = df_nulos[df_nulos['pct_nulos'] <= 85]['column_name'].tolist()

print(f'Total de {len(df_nulos)} colunas originais')
print(f'Total de {len(colunas_descarte)} colunas para descarte (>85% nulos)')
print(f'Total de {len(colunas_mantidas)} colunas mantidas (<=85% nulos)')

Total de 434 colunas originais
Total de 74 colunas para descarte (>85% nulos)
Total de 360 colunas mantidas (<=85% nulos)

In [4]:
df_emails = run_query("02_ordenar_emails.sql")
df_emails

       P_emaildomain  qtde_emails
0          gmail.com       228355
1          yahoo.com       100934
2                NaN        94456
3        hotmail.com        45250
4      anonymous.com        36998
5            aol.com        28289
6        comcast.net         7888
7         icloud.com         6267
8        outlook.com         5096
9            msn.com         4092
10           att.net         4033
11          live.com         3041
12     sbcglobal.net         2970
13       verizon.net         2705
14         ymail.com         2396
15     bellsouth.net         1909
16      yahoo.com.mx         1543
17            me.com         1522
18           cox.net         1393
19     optonline.net         1011
20       charter.net          816
21       live.com.mx          749
22    rocketmail.com          664
23          mail.com          559
24     earthlink.net          514
25             gmail          496
26        outlook.es          438
27           mac.com          436
28          juno.com          322
29           aim.com          315
30    roadrunner.com          305
31    windstream.net          305
32        hotmail.es          305
33        hotmail.fr          295
34      frontier.com          280
35    embarqmail.com          260
36            web.de          240
37           twc.com          230
38       netzero.com          230
39    prodigy.net.mx          207
40   centurylink.net          205
41       netzero.net          196
42   frontiernet.net          195
43             q.com          189
44    suddenlink.net          175
45        cfl.rr.com          172
46         sc.rr.com          164
47      cableone.net          159
48            gmx.de          149
49          yahoo.fr          143
50          yahoo.es          134
51     hotmail.co.uk          112
52    protonmail.com           76
53          yahoo.de           74
54           ptd.net           68
55           live.fr           56
56       yahoo.co.uk           49
57        hotmail.de           43
58  servicios-ta.com           35
59       yahoo.co.jp           32

In [13]:
agrupar_emails = run_query('03_agrupar_emails.sql')
agrupar_emails

   qtde_por_provedor categoria_provedor
0             228851             google
1              36998          anonymous
2              59477          microsoft
3             105969              yahoo
4              56564              outro
5               8225              apple
6              94456            missing