In [2]:
import duckdb
import sys
from pathlib import Path
import pandas as pd 

ROOT_DIR = Path.cwd().parent

if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))
    
    
from src.db.sql_runner import run_query

In [ ]:
df_nulos = run_query("01_nulls_check.sql")
df_nulos

In [4]:
colunas_descarte = df_nulos[df_nulos['pct_nulos'] > 85]['column_name'].tolist()

colunas_mantidas = df_nulos[df_nulos['pct_nulos'] <= 85]['column_name'].tolist()

print(f'Total de {len(df_nulos)} colunas originais')
print(f'Total de {len(colunas_descarte)} colunas para descarte (>85% nulos)')
print(f'Total de {len(colunas_mantidas)} colunas mantidas (<=85% nulos)')

Total de 434 colunas originais
Total de 74 colunas para descarte (>85% nulos)
Total de 360 colunas mantidas (<=85% nulos)

In [ ]:
df_emails = run_query("02_ordenar_emails.sql")
df_emails

In [6]:
agrupar_emails_comprador = run_query('03_agrupar_emails_comprador.sql')
agrupar_emails_comprador

   qtde_por_provedor categoria_provedor
0              59477          microsoft
1             105969              yahoo
2             228851             google
3              36998          anonymous
4              56564              outro
5              94456            missing
6               8225              apple

In [7]:
agrupar_emails_destino = run_query('04_agrupar_emails_destino.sql')
agrupar_emails_destino

   qtde_por_provedor categoria_provedor
0              57242             google
1              20529          anonymous
2              33604          microsoft
3              13967              yahoo
4             453249            missing
5               9777              outro
6               2172              apple

In [8]:
colunas_descarte = df_nulos[df_nulos['pct_nulos'] > 85]['column_name'].tolist()
colunas_descarte_str = ', '.join(colunas_descarte)
colunas_descarte_str

'id_24, id_07, id_08, id_21, id_25, id_26, id_22, id_23, id_27, dist2, D7, id_18, D13, D14, D12, id_03, id_04, D6, id_33, D8, D9, id_09, id_10, id_30, id_32, id_34, id_14, V138, V152, V158, V159, V160, V161, V162, V163, V164, V165, V166, V153, V157, V155, V148, V149, V139, V140, V150, V151, V154, V147, V141, V142, V143, V144, V145, V146, V156, V338, V339, V337, V322, V323, V324, V325, V336, V327, V328, V329, V330, V331, V332, V333, V334, V335, V326'

In [9]:
view_limpa = run_query("05_view_limpa.sql", colunas_descarte_str=colunas_descarte_str)
view_limpa

Empty DataFrame
Columns: [Count]
Index: []

In [ ]:
query_limpa = run_query('06_test_view.sql')
query_limpa